[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.install]
cmds = ['dotnet restore']

[phases.build]
cmds = ['dotnet publish PasteleriaCanelas.Api/PasteleriaCanelas.Api.csproj -c Release -o out']

[start]
cmd = 'dotnet out/PasteleriaCanelas.Api.dll'